package:
  name: feature_cuda
  version: {{ feature_cuda }}

build:
  number: 0
  string: {{ cuda_impl }}
  track_features:
    - feature_cuda_{{ cuda_impl }}

extra:
  recipe-maintainers:
    - v-turin
